import type { NearbyJob } from '../types/nearby-job.types';

export const MOCK_JOBS: NearbyJob[] = [
  {
    id: '1',
    serviceType: 'AC Deep Cleaning',
    title: 'Central Air Unit Maintenance',
    customerName: 'Robert Harrison',
    rating: 4.9,
    reviewCount: 12,
    location: 'Sector 52, Gurgaon',
    distance: 2.4,
    scheduledTime: 'Tomorrow, 10:00 AM',
    estimatedDuration: '2 Hours',
    payout: 120,
    priority: 'urgent',
    badge: 'AC Deep Cleaning',
  },
  {
    id: '2',
    serviceType: 'Kitchen Plumbing',
    title: 'Kitchen Sink & Tap Repair',
    customerName: 'Sarah Miller',
    rating: 4.7,
    reviewCount: 5,
    location: 'Green Valley Estates',
    distance: 4.1,
    scheduledTime: 'Today, 04:30 PM',
    estimatedDuration: '1 Hour',
    payout: 85,
    priority: 'normal',
    badge: 'Kitchen Plumbing',
  },
  {
    id: '3',
    serviceType: 'Electrical',
    title: 'Electrical Outlet Installation',
    customerName: 'Michael Chen',
    rating: 4.8,
    reviewCount: 8,
    location: 'DLF Cyber City',
    distance: 3.2,
    scheduledTime: 'Today, 02:00 PM',
    estimatedDuration: '1.5 Hours',
    payout: 95,
    priority: 'normal',
    badge: 'Electrical',
  },
  {
    id: '4',
    serviceType: 'Solar Cleaning',
    title: 'Solar Panel Cleaning & Inspection',
    customerName: 'Priya Sharma',
    rating: 5.0,
    reviewCount: 15,
    location: 'Sector 48, Gurgaon',
    distance: 1.8,
    scheduledTime: 'Tomorrow, 09:00 AM',
    estimatedDuration: '3 Hours',
    payout: 150,
    priority: 'scheduled',
    badge: 'Solar Cleaning',
  },
];
