import type { Service } from '@/types/services.types';

export const servicesData: Service[] = [
  {
    id: '1',
    slug: 'solar-panel-cleaning',
    badge: 'PROFESSIONAL SERVICE',
    title: 'Solar Cleaning',
    description:
      'Maximize your solar panel efficiency and longevity with professional cleaning.',
    price: 899,
    gridSize: { md: 5 },
    image: '/images/services/solar-cleaning.png',
    overview:
      'Keep your solar panels performing at their highest efficiency with our professional solar panel cleaning service. Our certified technicians use eco-friendly cleaning solutions and specialized equipment to ensure maximum performance.',
    includes: [
      'Panel Surface Cleaning',
      'Inverter Inspection',
      'Connection Check',
      'Performance Assessment',
      'Safety Inspection',
    ],
    ctaTitle: 'Ready To Book?',
    ctaDescription:
      'Schedule your service today and get professional assistance at your doorstep.',
    bookingForm: [
      {
        name: 'panelCount',
        label: 'Number of Solar Panels',
        type: 'number',
        required: true,
        placeholder: 'Enter number of panels',
        min: 1,
        max: 100,
        priceCalculation: {
          basePrice: 50,
          multiplier: 'panelCount',
        },
      },
      {
        name: 'propertyType',
        label: 'Property Type',
        type: 'select',
        required: true,
        options: [
          { value: 'residential', label: 'Residential', price: 0 },
          { value: 'commercial', label: 'Commercial', price: 200 },
        ],
      },
      {
        name: 'roofType',
        label: 'Roof Type',
        type: 'select',
        required: true,
        options: [
          { value: 'flat', label: 'Flat Roof' },
          { value: 'sloped', label: 'Sloped Roof' },
          { value: 'tiled', label: 'Tiled Roof' },
          { value: 'metal', label: 'Metal Roof' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'cleaningFrequency',
        label: 'Preferred Cleaning Frequency',
        type: 'select',
        required: true,
        options: [
          { value: 'monthly', label: 'Monthly', price: 0 },
          { value: 'quarterly', label: 'Quarterly', price: -100 },
          { value: 'half-yearly', label: 'Half-Yearly', price: -200 },
          { value: 'yearly', label: 'Yearly', price: -300 },
        ],
      },
      {
        name: 'lastCleaning',
        label: 'Last Cleaning Date',
        type: 'text',
        required: false,
        placeholder: 'When were they last cleaned? (Optional)',
      },
      {
        name: 'accessConcerns',
        label: 'Special Access Requirements',
        type: 'textarea',
        required: false,
        placeholder: 'Any special requirements for accessing the panels? (Optional)',
      },
    ],
    formConfig: {
      showPriceSummary: true,
      pricingEngine: 'solar',
      summaryFields: ['panelCount', 'propertyType', 'cleaningFrequency'],
    },
  },
  {
    id: '2',
    slug: 'ac-servicing',
    badge: 'EXPERT AC SERVICE',
    title: 'AC Servicing',
    description:
      'Complete AC inspection, cleaning and maintenance by certified technicians.',
    price: 699,
    gridSize: { md: 5 },
    image: '/images/services/ac-servicing.png',
    overview:
      'Ensure your air conditioner performs efficiently throughout the year with our comprehensive AC servicing. Our skilled technicians provide thorough cleaning and maintenance.',
    includes: [
      'Filter Cleaning',
      'Cooling Check',
      'Gas Inspection',
      'Drain Cleaning',
      'Performance Testing',
    ],
    ctaTitle: 'Ready To Book?',
    ctaDescription:
      'Book your AC service and stay comfortable all year round.',
    bookingForm: [
      {
        name: 'serviceType',
        label: 'Service Type',
        type: 'select',
        required: true,
        options: [
          { value: 'general-service', label: 'General Service', price: 599 },
          { value: 'repair', label: 'Repair', price: 799 },
          { value: 'gas-filling', label: 'Gas Filling', price: 1299 },
          { value: 'installation', label: 'Installation/Uninstallation', price: 1999 },
        ],
      },
      {
        name: 'acType',
        label: 'AC Type',
        type: 'select',
        required: true,
        options: [
          { value: 'split', label: 'Split AC' },
          { value: 'window', label: 'Window AC' },
          { value: 'cassette', label: 'Cassette AC' },
        ],
      },
      {
        name: 'brand',
        label: 'AC Brand',
        type: 'select',
        required: true,
        options: [
          { value: 'lg', label: 'LG' },
          { value: 'samsung', label: 'Samsung' },
          { value: 'daikin', label: 'Daikin' },
          { value: 'voltas', label: 'Voltas' },
          { value: 'hitachi', label: 'Hitachi' },
          { value: 'blue-star', label: 'Blue Star' },
          { value: 'carrier', label: 'Carrier' },
          { value: 'godrej', label: 'Godrej' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'issueDescription',
        label: 'Issue Description',
        type: 'textarea',
        required: true,
        placeholder: 'Please describe the issues you are facing with your AC in detail',
      },
      {
        name: 'photos',
        label: 'Upload Photos (Optional)',
        type: 'file',
        required: false,
        accept: 'image/*',
        multiple: true,
        maxFiles: 5,
      },
    ],
    formConfig: {
      showPriceSummary: true,
      pricingEngine: 'ac',
      summaryFields: ['serviceType', 'acType', 'brand'],
    },
  },
  {
    id: '3',
    slug: 'electrical-servicing',
    badge: 'EXPERT ELECTRICAL SERVICE',
    title: 'Electrical Servicing',
    description:
      'Complete electrical inspection, cleaning and maintenance by certified technicians.',
    price: 699,
    gridSize: { md: 5 },
    image: '/images/services/electrical.png',
    overview:
      'Ensure your electrical systems perform efficiently and safely throughout the year. Our certified electricians provide comprehensive electrical maintenance and safety checks.',
    includes: [
      'Wiring Inspection',
      'Circuit Breaker Check',
      'Outlet Testing',
      'Safety Assessment',
      'Performance Testing',
    ],
    ctaTitle: 'Ready To Book?',
    ctaDescription:
      'Book your electrical service and stay safe all year round.',
    bookingForm: [
      {
        name: 'serviceType',
        label: 'Type of Electrical Service',
        type: 'select',
        required: true,
        options: [
          { value: 'inspection', label: 'General Inspection' },
          { value: 'maintenance', label: 'Preventive Maintenance' },
          { value: 'repair', label: 'Repair Service' },
          { value: 'installation', label: 'New Installation' },
        ],
      },
      {
        name: 'propertyType',
        label: 'Property Type',
        type: 'select',
        required: true,
        options: [
          { value: 'residential', label: 'Residential' },
          { value: 'commercial', label: 'Commercial' },
          { value: 'industrial', label: 'Industrial' },
        ],
      },
      {
        name: 'urgencyLevel',
        label: 'Urgency Level',
        type: 'select',
        required: true,
        options: [
          { value: 'routine', label: 'Routine Maintenance' },
          { value: 'urgent', label: 'Urgent (24-48 hours)' },
          { value: 'emergency', label: 'Emergency (Same day)' },
        ],
      },
      {
        name: 'problemDescription',
        label: 'Problem Description',
        type: 'textarea',
        required: true,
        placeholder: 'Please describe the electrical work needed in detail',
      },
      {
        name: 'problemImages',
        label: 'Upload Problem Images',
        type: 'multi-file',
        required: false,
        accept: 'image/*',
        maxFiles: 10,
      },
      {
        name: 'materialRequirements',
        label: 'Material Requirement Notes',
        type: 'textarea',
        required: false,
        placeholder: 'Any specific materials or equipment you think might be needed? (Optional)',
      },
    ],
    formConfig: {
      showPriceSummary: false,
      pricingEngine: 'fixed',
      summaryFields: ['serviceType', 'propertyType', 'urgencyLevel'],
    },
  },
  {
    id: '4',
    slug: 'plumber-servicing',
    badge: 'EXPERT PLUMBER SERVICE',
    title: 'Plumber Servicing',
    description:
      'Complete plumber inspection, cleaning and maintenance by certified technicians.',
    price: 699,
    gridSize: { md: 5 },
    image: '/images/services/plumbing.png',
    overview:
      'Ensure your plumbing systems perform efficiently throughout the year. Our experienced plumbers provide comprehensive plumbing services for all your needs.',
    includes: [
      'Pipe Inspection',
      'Leak Detection',
      'Drain Cleaning',
      'Fixture Maintenance',
      'Performance Testing',
    ],
    ctaTitle: 'Ready To Book?',
    ctaDescription:
      'Book your plumbing service and maintain your systems year round.',
    bookingForm: [
      {
        name: 'serviceNeeded',
        label: 'Service Required',
        type: 'select',
        required: true,
        options: [
          { value: 'repair', label: 'Repair/Fix Issues' },
          { value: 'maintenance', label: 'Routine Maintenance' },
          { value: 'installation', label: 'New Installation' },
          { value: 'inspection', label: 'System Inspection' },
        ],
      },
      {
        name: 'problemArea',
        label: 'Problem Area',
        type: 'select',
        required: false,
        options: [
          { value: 'kitchen', label: 'Kitchen' },
          { value: 'bathroom', label: 'Bathroom' },
          { value: 'toilet', label: 'Toilet' },
          { value: 'pipes', label: 'Pipes' },
          { value: 'drainage', label: 'Drainage System' },
          { value: 'water-heater', label: 'Water Heater' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'urgencyLevel',
        label: 'Urgency Level',
        type: 'select',
        required: true,
        options: [
          { value: 'low', label: 'Low (Scheduled)' },
          { value: 'medium', label: 'Medium (Within 48 hours)' },
          { value: 'high', label: 'High (Within 24 hours)' },
          { value: 'emergency', label: 'Emergency (Immediate)' },
        ],
      },
      {
        name: 'problemDescription',
        label: 'Problem Description',
        type: 'textarea',
        required: true,
        placeholder: 'Please describe the plumbing issue in detail',
      },
      {
        name: 'problemImages',
        label: 'Upload Problem Images',
        type: 'multi-file',
        required: false,
        accept: 'image/*',
        maxFiles: 10,
      },
      {
        name: 'materialRequirements',
        label: 'Material Requirement Notes',
        type: 'textarea',
        required: false,
        placeholder: 'Any specific materials or parts you think might be needed? (Optional)',
      },
    ],
    formConfig: {
      showPriceSummary: false,
      pricingEngine: 'fixed',
      summaryFields: ['serviceNeeded', 'problemArea', 'urgencyLevel'],
    },
  },
];